apiVersion: v1
kind: Service
metadata:
  name: bookok99
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "bookok99"
    port: 8080
  selector:
    app: bookok99
